---
- name: Pull EC2 IMDSv1 metadata
  command: "curl -sL {{ promtail_aws_imdsv1_url }}/{{ item.value }}"
  register: _aws_imdsv1_result
  with_items: "{{ promtail_aws_imdsv1_data }}"

- name: print valuse
  debug:
    var: _aws_imdsv1

- name: Write EC2 IMDSv1 metadata to promtail environment file
  lineinfile:
    path: "{{ promtail_config_dir }}/{{ promtail_env_file }}"
    state: present
    line: "{{ item.key }}={{item.value}}"
  with_items: _aws_imdsv1_result


# - name: Check if certificates exists. | Webroot
#   stat:
#     path: /etc/letsencrypt/live/{{ item }}/cert.pem
#   register: _letsencrypt_certs
#   with_items: "{{ certbot_domains }}"

# - name: Generate new certificates if they do not exist. | Webroot
#   command: >-
#     {{ certbot_script }} certonly
#     --webroot
#     -w /var/www/html/
#     --noninteractive
#     --agree-tos
#     --email {{ certbot_email }}
#     -d {{ item.item }}
#   loop: "{{ _letsencrypt_certs.results }}"
#   when: not item.stat.exists



# run curl command for each var.ec2_tag and register result
# write each registered result to environmnet file