---
- name: Create promtail systemd service file
  template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    owner: root
    group: root
    mode: 0644
  notify: restart promtail

- name: Create/Update configuration file
  template:
    src: promtail-config.yml.j2
    dest: "{{ promtail_config_dir }}/{{ promtail_config_file }}"
    owner: root
    mode: 0644
  notify: restart promtail
