---
- import_tasks: preflight.yml
  tags:
    - promtail_install
    - promtail_configure
    - promtail_run

- import_tasks: install.yml
  become: true
  tags:
    - promtail_install

- import_tasks: configure.yml
  become: true
  tags:
    - promtail_configure

- name: Ensure promtail is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: promtail
    enabled: true
  tags:
    - promtail_run

- name: Force all handlers to run
  meta: flush_handlers

- name: Ensure promtail service is running
  service:
    name: promtail
    state: started
  become: true
  tags:
    - promtail_run
